# Generated by Django 5.0.4 on 2024-05-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('name', models.TextField(verbose_name='Имя')),
                ('phone', models.TextField(verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(verbose_name='Регион')),
                ('country', models.TextField(verbose_name='Страна')),
                ('place_name', models.TextField(verbose_name='Название места')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('name', models.TextField(verbose_name='Имя')),
                ('phone', models.TextField(verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excur.destination')),
                ('id_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excur.guide')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excur.client')),
                ('id_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excur.excursion_template')),
            ],
        ),
    ]
